name: "Lua Check"

on:
  push:
  pull_request:
  schedule:
    - cron: '36 3 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'lua' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Luarocks
      run: |
        sudo apt install luarocks

    - name: Install Luacheck
      run: |
        sudo luarocks install luacheck
        luacheck -v
        sudo luarocks install luafilesystem

    - name: Run LuaCheck
      run: |
        luacheck lib
