name: "Shell Check"

on:
  push:
  pull_request:
  schedule:
    - cron: '36 3 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'lua' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install ShellCheck
      run: |
        sudo apt install shellcheck

    - name: Run ShellCheck
      run: |
        shellcheck **/*.sh
